### ISSUE TITLE
Docker: Linux Spec Capabilities

### ISSUE THREAD

**Issue by carbotaniuman** [kylemanna/docker-openvpn#157]
I'm trying to run this command.
`docker run -v $OVPN_DATA:/etc/openvpn -d -p 1194:1194/udp --cap-add=NET_ADMIN kylemanna/openvpn
`
However, every time I try to run this I get:
`docker: Error response from daemon: linux spec capabilities: Unknown capability to add "CAP_NET_ADMIN `

I'm running a precompiled binary on Vultr's platform (the storage node), and I'm wondering what the issue might be. Any help?

Specs:

Docker Version: 1.11.2
CentOS 7

**Comment by kylemanna** [comment]
Perhaps it's a CentOS 7 bug.  I'm running Ubuntu 16.04.01 on a VULTR storage node and works.  Tested with:

    docker run -v $OVPN_DATA:/etc/openvpn -p 1194:1194/udp --cap-add=NET_ADMIN kylemanna/openvpn openvpn --version

Docker: 1.12.1
Kernel 4.4.0-36

Another option might be to replace `--cap-add=NET_ADMIN` with `--privileged` but it offers less granular control.

**Comment by carbotaniuman** [comment]
The workaround works. Is it related to the kernel? I'm kernel 3.10

**Comment by carbotaniuman** [comment]
In addition, I also get bash: CLIENTNAME.txt: permission denied when running the command:
`docker run -v $OVPN_DATA:/etc/openvpn --rm kylemanna/openvpn ovpn_getclient CLIENTNAME > CLIENTNAME.ovpn
`

IS it related?

**Comment by kylemanna** [comment]
> The workaround works. Is it related to the kernel? I'm kernel 3.10

Could be, earlier versions of docker didn't have `--cap-add` and perhaps your kernel which seems ancient didn't have the underlying support.  Workaround is probably just fine, proper fix is to run a newer kernel or distribution, but if you're attached to CentOS I'd stick with the workaround.

> In addition, I also get bash: CLIENTNAME.txt: permission denied when running the command:
docker run -v $OVPN_DATA:/etc/openvpn --rm kylemanna/openvpn ovpn_getclient CLIENTNAME > CLIENTNAME.ovpn

This actually has nothing to do with docker.  The `>` redirects stdout from the executable (in this case docker) to a file instead of displaying it on the screen.  In you invocation it's attempting to write to `CLIENTNAME.ovpn` in the working directory that your current user doesn't have sufficient file permissions to write to.  Change the file path to somewhere you have permissions to, like your `$HOME` directory.

Search Google for `shell  input and output redirection` to learn more.
