### ISSUE TITLE
Performance on Raspberry Pi 3

### ISSUE THREAD

**Issue by nodesocket** [kylemanna/docker-openvpn#168]
Has anybody run docker-openvpn on a Raspberry Pi 3? Curious to see what sort of throughput I can expect. Any limit to the number of simultaneous connected clients?

**Comment by kylemanna** [comment]
I'd assume it'd be very CPU constrained.  For reference a $5/mo DO droplet is CPU limited.  1 core ~ 100Mb/s.  I'd assume that the RPi3 would be considerably worse at encryption + decryption.

Do you have a performance goal in mind?

**Comment by kylemanna** [comment]
Found a [blog post on the topic](https://www.hackviking.com/single-board-computers/openvpn-performance-on-the-pi/):

>Raspberry Pi 3 Model B (1.2Ghz quad core, 1Gb memory, 100Mbit-nic)
>Down: 12.16 Mb/s
>Up: 3.59 Mb/s

**Comment by nodesocket** [comment]
Those throughout numbers for the pi actually seem good, since a high end laptop was only able to do:

Laptop running the OpenVPN client (Dell Precision M4800, 2.5Ghz 8 cores, 32Gb memory, Gbit-nic)
Down: 19.13 Mb/s
Up: 10.02

Curious how much throughout I'll lose by using docker.

Will setup and report back.

**Comment by kylemanna** [comment]
@nodesocket Another thing to consider is that I doubt that openvpn is multi-threaded, so the multiple cores of the laptop probably aren't helping for a single client.

As for throughput due to Docker, I'd imagine the overhead would be pretty minimal.  Docker creates namespaces per process rather then emulating another CPU.

Also checkout https://github.com/kylemanna/docker-openvpn/issues/19 and perhaps performance could be improved by tweaks, but nobody has expressed concern, contributed any tests and I haven't had time to satisfy my own curiosity.

**Comment by kylemanna** [comment]
Closing due to no updates in a few months.
