### ISSUE TITLE
DD-WRT config

### ISSUE THREAD

**Issue by pjbish** [kylemanna/docker-openvpn#177]
Thanks for this.

Has anyone got it running on a DD-WRT router ? If so, would you be able to share the config or a screen shot of the parameters on the router ?

Any help would be appreciated.

**Comment by colthreepv** [comment]
No, but I got it running on a Tomato Shibby firmware with VPN support

**Comment by kylemanna** [comment]
Looks like this is just a matter of copying and pasting fields in to the *OpenVPN Client* section of the router config with the Advanced Options checked.  Should be able to translate form the config file to the configuration options, but I haven't tested.

Also, include observations or issues so that other might help troubleshoot.
