### ISSUE TITLE
Container builds need work ...

### ISSUE THREAD

**Issue by gegere** [kylemanna/docker-openvpn#24]
I spent most of the day working at this and following your instructions. I think you did a great job but there are a few issue and I ended up using [the build](https://github.com/rsc-1/dispos-a-vpn) from [rsc-1/dispos-a-vpn](https://github.com/rsc-1/dispos-a-vpn)

I appreciate the time and effort you put into your build, cheers!

**Comment by kylemanna** [comment]
Thanks for the feedback. Any insight on what the errors were?

By the way, the repo you linked to do anything to encrypt the transport
data since the user apparently disabled it:

https://github.com/akanto/dockvpn/commit/7977c70a827aed6c3e28ebf451493b27415c3717

Thought that was an interesting way to run a VPN.

**Comment by gegere** [comment]
The errors had todo with the TLS certificate not being read by Tunnelblick, I actually sent you a email directly. I would be happy to share more. I am updating the readme of another repo testing and will commit soon, after my tests.

The link you provided was my fault, I linked correctly. Yeah disabling encryption is bad!

[This is the correct repo](https://github.com/rsc-1/dispos-a-vpn)

**Comment by gegere** [comment]
phew... hours later! I have create an [updated repo](https://github.com/htmlgraphic/OpenVPN-Server) using your data container idea with the corrections from [rsc-1](https://github.com/rsc-1/dispos-a-vpn)

Maybe we could combine forces. I noticed many bad practices with some of these builds.

**Comment by kylemanna** [comment]
Glad to hear you got it working!

> I noticed many bad practices with people branching off the initial build.

The initial build was a bad idea for production systems and appears to be meant as a blog post and proof of concept.  Static shared keys?  Key distribution via unauthenticated https?  I need not say more as these have been resolved in my image for a long time.

> Maybe we could combine forces.

As for combining, I accept pull requests that fix documentation clarification or bugs!  Feel free to send them this way.

I'm closing this issue because there is nothing actionable here.

**Comment by gegere** [comment]
I agree. The initial was a simple start. I will issue a pull request to you but it is messy with commits.

**Comment by kylemanna** [comment]
>I agree. The initial was a simple start. I will issue a pull request to you but
>it is messy with commits.

Sounds good.  Please squash your commits so they are coherent and
concise.
