### ISSUE TITLE
Can't create new user cert

### ISSUE THREAD

**Issue by degritsenko** [kylemanna/docker-openvpn#379]
Hello!

> root@gritsenko ~ # docker run -v $OVPN_DATA:/etc/openvpn --rm -it kylemanna/openvpn easyrsa build-client-full kutakov nopass
> 
> Easy-RSA error:
> 
> EASYRSA_PKI does not exist (perhaps you need to run init-pki)?
> Expected to find the EASYRSA_PKI at: /etc/openvpn/pki
> Run easyrsa without commands for usage and command help.

**Comment by degritsenko** [comment]
my bad

**Comment by Alikhll** [comment]
@degritsenko  
How did you solve that?

**Comment by eastabrooka** [comment]
I got this same error, It was because I was following 
https://hub.docker.com/r/kylemanna/openvpn/
Guide, and did not run 
docker run -v $OVPN_DATA:/etc/openvpn --log-driver=none --rm -it kylemanna/openvpn ovpn_initpki

The "My Bad" from degritsenko was probably because of a missed command. 
I am posting this because - It may help anyone else who falls into this trap !
