### ISSUE TITLE
Can't ping the clients and have some issues when starting the container with docker-compose 

### ISSUE THREAD

**Issue by echtelerp** [kylemanna/docker-openvpn#526]
openvpn    | iptables: No chain/target/match by that name.
openvpn    | iptables: No chain/target/match by that name.
openvpn    | iptables: No chain/target/match by that name.
openvpn    | iptables: No chain/target/match by that name.
openvpn    | Enabling IPv6 Forwarding
openvpn    | sysctl: error setting key 'net.ipv6.conf.all.disable_ipv6': Read-only file system
openvpn    | Failed to enable IPv6 support
openvpn    | sysctl: error setting key 'net.ipv6.conf.default.forwarding': Read-only file system
openvpn    | Failed to enable IPv6 Forwarding default
openvpn    | sysctl: error setting key 'net.ipv6.conf.all.forwarding': Read-only file system
openvpn    | Failed to enable IPv6 Forwarding
openvpn    | Running 'openvpn --config /etc/openvpn/openvpn.conf --crl-verify /etc/openvpn/crl.pem '
openvpn    | Mon Oct 21 17:58:12 2019 WARNING: file '/etc/openvpn/pki/private/echteler.org.key' is group or others accessible
openvpn    | Mon Oct 21 17:58:12 2019 WARNING: file '/etc/openvpn/pki/ta.key' is group or others accessible
openvpn    | Mon Oct 21 17:58:12 2019 OpenVPN 2.4.6 armv6-alpine-linux-musleabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Dec 14 2018
openvpn    | Mon Oct 21 17:58:12 2019 library versions: OpenSSL 1.1.1a  20 Nov 2018, LZO 2.10
openvpn    | Mon Oct 21 17:58:12 2019 Diffie-Hellman initialized with 2048 bit key
openvpn    | Mon Oct 21 17:58:12 2019 Outgoing Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
openvpn    | Mon Oct 21 17:58:12 2019 Incoming Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
openvpn    | Mon Oct 21 17:58:12 2019 ROUTE_GATEWAY 172.19.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:13:00:02
openvpn    | Mon Oct 21 17:58:12 2019 TUN/TAP device tun0 opened
openvpn    | Mon Oct 21 17:58:12 2019 TUN/TAP TX queue length set to 100
openvpn    | Mon Oct 21 17:58:12 2019 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
openvpn    | Mon Oct 21 17:58:12 2019 /sbin/ip link set dev tun0 up mtu 1500
openvpn    | Mon Oct 21 17:58:12 2019 /sbin/ip addr add dev tun0 local 192.168.255.1 peer 192.168.255.2
openvpn    | Mon Oct 21 17:58:12 2019 /sbin/ip route add 192.168.254.0/24 via 192.168.255.2
openvpn    | Mon Oct 21 17:58:12 2019 /sbin/ip route add 192.168.255.0/24 via 192.168.255.2
openvpn    | Mon Oct 21 17:58:12 2019 Could not determine IPv4/IPv6 protocol. Using AF_INET
openvpn    | Mon Oct 21 17:58:12 2019 Socket Buffers: R=[163840->163840] S=[163840->163840]

has anyone else have an Idea, what I can do? I tried several changes in the conf file... 
specially the 3 errors on the beginning is confusing me

**Comment by echtelerp** [comment]
iptables: No chain/target/match by that name.
iptables: No chain/target/match by that name.
iptables: No chain/target/match by that name.
iptables: No chain/target/match by that name.

specially this is odd.. 

if I bash inside the container I get: 

/ # iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

**Comment by lippl** [comment]
unfortunately I get similar output, but havent found a solution or reason yet:
openvpn_udp_1  | iptables v1.8.3 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
openvpn_udp_1  | Perhaps iptables or your kernel needs to be upgraded.
openvpn_udp_1  | iptables v1.8.3 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
openvpn_udp_1  | Perhaps iptables or your kernel needs to be upgraded.
openvpn_udp_1  | iptables v1.8.3 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
openvpn_udp_1  | Perhaps iptables or your kernel needs to be upgraded.
openvpn_udp_1  | Enabling IPv6 Forwarding
openvpn_udp_1  | sysctl: error setting key 'net.ipv6.conf.all.disable_ipv6': Read-only file system
openvpn_udp_1  | Failed to enable IPv6 support
openvpn_udp_1  | sysctl: error setting key 'net.ipv6.conf.default.forwarding': Read-only file system
openvpn_udp_1  | Failed to enable IPv6 Forwarding default
openvpn_udp_1  | sysctl: error setting key 'net.ipv6.conf.all.forwarding': Read-only file system
openvpn_udp_1  | Failed to enable IPv6 Forwarding
openvpn_udp_1  | Running 'openvpn --config /etc/openvpn/openvpn.conf --client-config-dir /etc/openvpn/ccd --crl-verify /etc/openvpn/crl.pem '
openvpn_udp_1  | Mon Oct 21 17:40:36 2019 OpenVPN 2.4.7 armv7-alpine-linux-musleabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  5 2019
openvpn_udp_1  | Mon Oct 21 17:40:36 2019 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10
openvpn_udp_1  | Mon Oct 21 17:40:36 2019 Diffie-Hellman initialized with 2048 bit key
openvpn_udp_1  | Mon Oct 21 17:40:36 2019 Outgoing Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
openvpn_udp_1  | Mon Oct 21 17:40:36 2019 Incoming Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
openvpn_udp_1  | Mon Oct 21 17:40:36 2019 ROUTE_GATEWAY 172.25.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:19:00:03
openvpn_udp_1  | Mon Oct 21 17:40:36 2019 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such device (errno=19)
openvpn_udp_1  | Mon Oct 21 17:40:36 2019 Exiting due to fatal error

**Comment by echtelerp** [comment]
openvpn_udp_1 | Enabling IPv6 Forwarding
openvpn_udp_1 | sysctl: error setting key 'net.ipv6.conf.all.disable_ipv6': Read-only file system
openvpn_udp_1 | Failed to enable IPv6 support
openvpn_udp_1 | sysctl: error setting key 'net.ipv6.conf.default.forwarding': Read-only file system
openvpn_udp_1 | Failed to enable IPv6 Forwarding default
openvpn_udp_1 | sysctl: error setting key 'net.ipv6.conf.all.forwarding': Read-only file system
openvpn_udp_1 | Failed to enable IPv6 Forwarding

for this I found the solution: 
You have to make the container prevailed :-)

the other problems I am still searching for a solution :-(

**Comment by echtelerp** [comment]
iptables -t nat -C POSTROUTING -s $OVPN_SERVER -o $OVPN_NATDEVICE -j MASQUERADE
seems from an earlier post, that this is the root cause? 
it is in the env.sh file...

**Comment by VEDA95** [comment]
I've been having this same exact issue too. After hours of wracking my brain over iptable rule i'm completely stumped.

**Comment by echtelerp** [comment]
true :-) I already try for about a week now. 
now I try all over again with a totally new fresh clean install of my raspberry...

**Comment by echtelerp** [comment]
okay, so what I found out today: the cmd output: 
iptables: No chain/target/match by that name.
iptables: No chain/target/match by that name.
iptables: No chain/target/match by that name.
iptables: No chain/target/match by that name. ....

is due tu the check rule within the oven_run.sh script. 
the script checks if the rules are existent, otherwise it generates them... 
so this output seems to be normal... 
from the search here the explanations, what the function in line 41 to 49 does... 
-A, --append chain rule-specification
Append one or more rules to the end of the selected chain. When the source and/or destination names resolve to more than one address, a rule will be added for each possible address combination.
-C, --check chain rule-specification
Check whether a rule matching the specification does exist in the selected chain. This command uses the same logic as -D to find a matching entry, but does not alter the existing iptables configuration and uses its exit code to indicate success or failure.

more research tomorrow :-)

**Comment by echtelerp** [comment]
route -n on the clean install before starting the vpn container shows: 

Ziel            Router          Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.2.1     0.0.0.0         UG    202    0        0 eth0
0.0.0.0         192.168.2.1     0.0.0.0         UG    303    0        0 wlan0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.2.0     0.0.0.0         255.255.255.0   U     202    0        0 eth0
192.168.2.0     0.0.0.0         255.255.255.0   U     303    0        0 wlan0

**Comment by lippl** [comment]
Thanks for all your research so far!

What do you mean by this? DO you mean run it privileged?
> You have to make the container prevailed :-)

**Comment by echtelerp** [comment]
sorry typo, yes. you need to run it in privileged mode.

**Comment by echtelerp** [comment]
some more research... :-) 

inside the host: 


**/ # iptables -L -n -v
Chain INPUT (policy ACCEPT 119 packets, 20029 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy ACCEPT 78 packets, 19381 bytes)
 pkts bytes target     prot opt in     out     source               destination         
  310 38807 ACCEPT     all  --  tun+   *       0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  tun0   *       0.0.0.0/0            0.0.0.0/0           

Chain OUTPUT (policy ACCEPT 91 packets, 27273 bytes)
 pkts bytes target     prot opt in     out     source               destination         
/ # 
/ # 
/ # iptables -t nat -L -n -v
Chain PREROUTING (policy ACCEPT 293 packets, 24137 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain INPUT (policy ACCEPT 43 packets, 6526 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 7 packets, 540 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 7 packets, 540 bytes)
 pkts bytes target     prot opt in     out     source               destination         
  234 15251 MASQUERADE  all  --  *      eth0    192.168.255.0/24     0.0.0.0/0           
    0     0 MASQUERADE  all  --  *      eth0    192.168.254.0/24     0.0.0.0/0           
/ # **

**Comment by echtelerp** [comment]
Will start over again, when I found the root cause of my issue
