### ISSUE TITLE
Use tag version instead of latest

### ISSUE THREAD

**Issue by rdcavanha** [kylemanna/docker-openvpn#651]
Could you please consider using tags instead of `latest`? It makes nearly impossible to rollback to a previous version in case something goes wrong when using `latest`.

P.S.: I see, for instance, that `latest` and `2.4` were pushed around the same time, but their digest don't match.

**Comment by kylemanna** [comment]
Probably not. To hard to maintain TBH. Just don't have the time to maintain an armada of branches and tags.

I'd rather remove features and improve testing so it's unlikely things go wrong.

**Comment by petemyron** [comment]
It's the removing of tags that's getting me. For example, 2.5 _did_ exist, but now it doesn't. Using latest can lead to breakages when the configuration file requires changes. Understandable about the time to maintain, though. Otherwise, thanks for providing all of this. Docker Hub says 1 _billion_ + downloads.

**Comment by BrodyStone21** [comment]
> It's the removing of tags that's getting me. For example, 2.5 _did_ exist, but now it doesn't. Using latest can lead to breakages when the configuration file requires changes. Understandable about the time to maintain, though. Otherwise, thanks for providing all of this. Docker Hub says 1 _billion_ + downloads.

I did NOT believe you so I was about to Google it just say that you were wrong and it MUST be 1 Million+ but holy shit

This guy's a legend.
