### ISSUE TITLE
Unexpected termination

### ISSUE THREAD

**Issue by AntouanK** [kylemanna/docker-openvpn#96]
Been using the openvpn docker for a week now, on a 5$ DO VM.
This morning, I had trouble connecting to my VPN. So I logged into my VM to see that the container running `kylemanna/openvpn` had stopped.

Here's the lines of the logs for 09:44, when it apparently exited the process.
```
Thu Jan 21 09:44:18 2016 event_wait : Interrupted system call (code=4)
Thu Jan 21 09:44:18 2016 /sbin/ip route del 192.168.255.0/24
RTNETLINK answers: Operation not permitted
RTNETLINK answers: Operation not permitted
Thu Jan 21 09:44:18 2016 ERROR: Linux route delete command failed: external program exited with error status: 2
Thu Jan 21 09:44:18 2016 /sbin/ip route del 192.168.254.0/24
Thu Jan 21 09:44:18 2016 ERROR: Linux route delete command failed: external program exited with error status: 2
Thu Jan 21 09:44:18 2016 Closing TUN/TAP interface
Thu Jan 21 09:44:18 2016 /sbin/ip addr del dev tun0 local 192.168.255.1 peer 192.168.255.2
RTNETLINK answers: Operation not permitted
Thu Jan 21 09:44:18 2016 Linux ip addr del failed: external program exited with error status: 2
Thu Jan 21 09:44:18 2016 SIGTERM[hard,] received, process exiting
```

I restarted it and it works fine, just posting the logs to see if there's something I missed or some bug.

**Comment by kylemanna** [comment]
Something else signaled it to exit as it received a SIGTERM.  Something on your system sent a SIGTERM, I'd look for that. Did you run out of memory or something on your VM?  Did docker try to cleanly shut down a container?

The errors about being unable to delete the routes and addresses are expected since the daemon doesn't run as root.  When the container closes the instant later the network config is cleaned up by the kernel.

**Comment by AntouanK** [comment]
Turns out it was CoreOS rebooting to get security updates...
Sorry for that.
